[package]
name = "keyd"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
env_logger = "0.11.6"
hidapi = "2.6.3"
log = "0.4.22"
sysinfo = "0.33.1"
tokio = { version = "1", features = ["full"] }
